### ISSUE TITLE
What do I do with this "ipdb>" screen or error?

### ISSUE THREAD

**Issue by ProGamerGov** [hanzhanggit/StackGAN#1]
So I installed StackGAN using this [guide](https://www.reddit.com/r/deepdream/comments/5kz8xp/stackgan_text_to_photorealistic_image_synthesis/dbru5wa/), but I am unsure of what do with the screen/error that ipdb creates?

```
ubuntu@ip-Address:~/StackGAN$ sh demo/birds_demo.sh
{
  doc_length : 201
  filenames : "Data/birds/example_captions.t7"
  queries : "Data/birds/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_nc4_cub_hybrid_gru18_a1_c512_0.00070_1_10_trainvalids.txt_iter30000.t7"
}
Successfully load sentences from:  Data/birds/example_captions.t7
Total number of sentences: 6
num_embeddings: 6 (6, 1024)
lr_imsize:  64
--Return--
None
> /home/ubuntu/StackGAN/misc/custom_ops.py(136)__call__()
    132                                        init=tf.random_normal_initializer(stddev=stddev))
    133                 bias = self.variable("bias", [output_size], init=tf.constant_initializer(bias_start))
    134                 return input_layer.with_tensor(tf.matmul(input_, matrix) + bias, parameters=self.vars)
    135         except Exception:
--> 136             import ipdb; ipdb.set_trace()

ipdb>

```

**Comment by ProGamerGov** [comment]
The ipdb comes from a file located at: StackGAN/misc/custom_ops.py, on line 136. 

```
@pt.Register
class custom_fully_connected(pt.VarStoreMethod):
    def __call__(self, input_layer, output_size, scope=None, in_dim=None, stddev=0.02, bias_start=0.0):
        shape = input_layer.shape
        input_ = input_layer.tensor
        try:
            if len(shape) == 4:
                input_ = tf.reshape(input_, tf.pack([tf.shape(input_)[0], np.prod(shape[1:])]))
                input_.set_shape([None, np.prod(shape[1:])])
                shape = input_.get_shape().as_list()

            with tf.variable_scope(scope or "Linear"):
                matrix = self.variable("Matrix", [in_dim or shape[1], output_size], dt=tf.float32,
                                       init=tf.random_normal_initializer(stddev=stddev))
                bias = self.variable("bias", [output_size], init=tf.constant_initializer(bias_start))
                return input_layer.with_tensor(tf.matmul(input_, matrix) + bias, parameters=self.vars)
        except Exception:
            import ipdb; ipdb.set_trace()
```

**Comment by ProGamerGov** [comment]
Typing "continue" on the ipdb menu results in: 

```

ubuntu@ip-Address:~/StackGAN$ sh demo/birds_demo.sh
{
  doc_length : 201
  filenames : "Data/birds/example_captions.t7"
  queries : "Data/birds/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_nc4_cub_hybrid_gru18_a1_c512_0.00070_1_10_trainvalids.txt_iter30000.t7"
}
Successfully load sentences from:  Data/birds/example_captions.t7
Total number of sentences: 6
num_embeddings: 6 (6, 1024)
lr_imsize:  64
--Return--
None
> /home/ubuntu/StackGAN/misc/custom_ops.py(136)__call__()
    134                 return input_layer.with_tensor(tf.matmul(input_, matrix) + bias, parameters=self.vars)
    135         except Exception:
--> 136             import ipdb; ipdb.set_trace()
    137
    138

ipdb> continue
Traceback (most recent call last):
  File "demo/demo.py", line 192, in <module>
    build_model(sess, embeddings.shape[-1], batch_size)
  File "demo/demo.py", line 62, in build_model
    c = sample_encoded_context(embeddings, model)
  File "demo/demo.py", line 40, in sample_encoded_context
    c_mean_logsigma = model.generate_condition(embeddings)
  File "/home/ubuntu/StackGAN/stageII/model.py", line 47, in generate_condition
    custom_fully_connected(self.ef_dim * 2).
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 1971, in method
    return input_layer._method_complete(result)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 691, in _method_complete
    return self.with_tensor(result)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 976, in with_tensor
    layer = Layer(copy=self, tensor=unwrap(tensor), sequence=None)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 931, in __init__
    self._name = self._sequence[0].op.name
TypeError: 'NoneType' object has no attribute '__getitem__'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by ProGamerGov** [comment]
Doing "Ctrl + D" on the ipdb menu results in:

```
ubuntu@ip-Address:~/StackGAN$ sh demo/birds_demo.sh                                                            {
  doc_length : 201
  filenames : "Data/birds/example_captions.t7"
  queries : "Data/birds/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_nc4_cub_hybrid_gru18_a1_c512_0.00070_1_10_trainvalids.txt_iter30000.t7"
}
Successfully load sentences from:  Data/birds/example_captions.t7
Total number of sentences: 6
num_embeddings: 6 (6, 1024)
lr_imsize:  64
--Return--
None
> /home/ubuntu/StackGAN/misc/custom_ops.py(136)__call__()
    134                 return input_layer.with_tensor(tf.matmul(input_, matrix) + bias, parameters=self.vars)
    135         except Exception:
--> 136             import ipdb; ipdb.set_trace()
    137
    138

ipdb>

Traceback (most recent call last):
  File "demo/demo.py", line 192, in <module>
    build_model(sess, embeddings.shape[-1], batch_size)
  File "demo/demo.py", line 62, in build_model
    c = sample_encoded_context(embeddings, model)
  File "demo/demo.py", line 40, in sample_encoded_context
    c_mean_logsigma = model.generate_condition(embeddings)
  File "/home/ubuntu/StackGAN/stageII/model.py", line 47, in generate_condition
    custom_fully_connected(self.ef_dim * 2).
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 1970, in method
    result = func(non_seq_layer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 691, in _method_complete
    return self.with_tensor(result)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 976, in with_tensor
    layer = Layer(copy=self, tensor=unwrap(tensor), sequence=None)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 931, in __init__
    self._name = self._sequence[0].op.name
TypeError: 'NoneType' object has no attribute '__getitem__'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

ubuntu@ip-Address:~/StackGAN$

```

**Comment by ProGamerGov** [comment]
Rebooting seems to have resulted in a failure to import a module called "misc.config". But the ipdb error is no longer present, at least until the misc.config error is resolved.

**Comment by ProGamerGov** [comment]
The error when using the GPU version of Tensorflow: 

```
ubuntu@ip-Address:~/StackGAN$ sh demo/birds_demo.sh
{
  doc_length : 201
  filenames : "Data/birds/example_captions.t7"
  queries : "Data/birds/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_nc4_cub_hybrid_gru18_a1_c512_0.00070_1_10_trainvalids.txt_iter30000.t7"
}
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Successfully load sentences from:  Data/birds/example_captions.t7
Total number of sentences: 6
num_embeddings: 6 (6, 1024)
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
lr_imsize:  64
--Return--
None
> /home/ubuntu/StackGAN/misc/custom_ops.py(136)__call__()
    134                 return input_layer.with_tensor(tf.matmul(input_, matrix) + bias, parameters=self.vars)
    135         except Exception:
--> 136             import ipdb; ipdb.set_trace()
    137
    138

ipdb> continue
Traceback (most recent call last):
  File "demo/demo.py", line 192, in <module>
    build_model(sess, embeddings.shape[-1], batch_size)
  File "demo/demo.py", line 62, in build_model
    c = sample_encoded_context(embeddings, model)
  File "demo/demo.py", line 40, in sample_encoded_context
    c_mean_logsigma = model.generate_condition(embeddings)
  File "/home/ubuntu/StackGAN/stageII/model.py", line 47, in generate_condition
    custom_fully_connected(self.ef_dim * 2).
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 1971, in method
    return input_layer._method_complete(result)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 691, in _method_complete
    return self.with_tensor(result)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 976, in with_tensor
    layer = Layer(copy=self, tensor=unwrap(tensor), sequence=None)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 931, in __init__
    self._name = self._sequence[0].op.name
TypeError: 'NoneType' object has no attribute '__getitem__'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

ubuntu@ip-Addresss:~/StackGAN$
```

**Comment by Zardinality** [comment]
Try update your tensorflow to 0.11.0 if yours is in a lower version, it fix the same problem in my case.

**Comment by ProGamerGov** [comment]
@Zardinality The latest version of Tensorflow is 0.12.1 as per the installation guide [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md). Are you using 0.11.0 exactly? Or something like 0.11.2?

I used the following command to install Tensorflow version 0.11.0:

 `export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl`

And then `sudo pip install --upgrade $TF_BINARY_URL` to install Tensorflow version 0.11.0

**Comment by Zardinality** [comment]
@ProGamerGov Yes, forgot to mention it. I used pip and a open source mirror to directly install Tensorflow 0.12.1, on linux, using:
`pip install tensorflow==0.12.1`

**Comment by ProGamerGov** [comment]
@Zardinality Thanks, I'll try Tensorflow 0.12.1 and see if that solves the problem.

**Comment by ProGamerGov** [comment]
So I tried running `sudo pip uninstall tensorflow`, and then `sudo pip install tensorflow==0.12.1`. 

Now I have this error which seems to be related to the PIL package, which was replaced by the Pillow package:

```
ubuntu@ip-Address:~/StackGAN$ sh demo/birds_demo.sh                        {
  doc_length : 201
  filenames : "Data/birds/example_captions.t7"
  queries : "Data/birds/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_nc4_cub_hybrid_gru18_a1_c512_0.00070_1_10_trainvalids.txt_iter30000.t7"
}
Successfully load sentences from:  Data/birds/example_captions.t7
Total number of sentences: 6
num_embeddings: 6 (6, 1024)
lr_imsize:  64
Reading model parameters from ./models/birds_model_164000.ckpt
WARNING:tensorflow:From demo/demo.py:72 in build_model.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Traceback (most recent call last):
  File "demo/demo.py", line 217, in <module>
    count, save_dir)
  File "demo/demo.py", line 160, in save_super_images
    superimage = drawCaption(np.uint8(superimage), captions_batch[j])
  File "demo/demo.py", line 82, in drawCaption
    fnt = ImageFont.truetype('Pillow/Tests/fonts/FreeMono.ttf', 50)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource
ubuntu@ip-Address:~/StackGAN$

**Comment by ProGamerGov** [comment]
I installed these dependencies: 

```
sudo pip install prettytensor
sudo pip install progressbar
sudo pip install python-dateutil
sudo pip install easydict
sudo pip install pandas
sudo pip install torchfile
sudo pip install scipy
sudo pip install Pillow
sudo pip install pyyaml
sudo pip install ipdb
```

And I had Torch previously installed for [Neural-Style](https://github.com/jcjohnson/neural-style).

I then added StackGAN to my PYTHONPATH: 

```
export PYTHONPATH=$PYTHONPATH:/home/ubuntu/StackGAN/
export PYTHONPATH=$PYTHONPATH:/home/ubuntu/StackGAN
```

And I placed the models in their appropriate directories.

**Comment by ProGamerGov** [comment]
I found the solution to the problem. 

`sudo apt-get install ttf-freefont`

I guess Amazon AMIs don't have the default font installed.

**Comment by bearpaw** [comment]
Thanks. It works for me!

**Comment by peteratef342** [comment]
@ProGamerGov  how do you solve the example_captions.t7 problem ??
