### ISSUE TITLE
Is it possible to increase the output image size?

### ISSUE THREAD

**Issue by ProGamerGov** [hanzhanggit/StackGAN#3]
How would I increase the output image size so that each bird is at a higher resolution?

**Comment by ProGamerGov** [comment]
I tried changing both ` __C.TEST.LR_IMSIZE = 64` and `__C.TEST.HR_IMSIZE = 128` located in the `StackGAN/misc/config.py` file, but it results in the below error:

```
ubuntu@ip-Address:~/StackGAN$ sh demo/flowers_demo.sh
{
  doc_length : 201
  filenames : "Data/flowers/example_captions.t7"
  queries : "Data/flowers/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_flowers_c10_hybrid_0.00070_1_10_trainvalids.txt_iter16400.t7"
}
Successfully load sentences from:  Data/flowers/example_captions.t7
Total number of sentences: 5
num_embeddings: 5 (5, 1024)
lr_imsize:  128
Reading model parameters from ./models/flowers_model_130000.ckpt
WARNING:tensorflow:From demo/demo.py:72 in build_model.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Traceback (most recent call last):
  File "demo/demo.py", line 192, in <module>
    build_model(sess, embeddings.shape[-1], batch_size)
  File "demo/demo.py", line 73, in build_model
    saver.restore(sess, ckt_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [228,65536] rhs shape= [228,16384]
         [[Node: save/Assign_48 = Assign[T=DT_FLOAT, _class=["loc:@g_net/custom_fully_connected_1/Linear/Matrix"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](g_net/custom_fully_connected_1/Linear/Matrix, save/RestoreV2_48)]]

Caused by op u'save/Assign_48', defined at:
  File "demo/demo.py", line 192, in <module>
    build_model(sess, embeddings.shape[-1], batch_size)
  File "demo/demo.py", line 72, in build_model
    saver = tf.train.Saver(tf.all_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 373, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 130, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [228,65536] rhs shape= [228,16384]
         [[Node: save/Assign_48 = Assign[T=DT_FLOAT, _class=["loc:@g_net/custom_fully_connected_1/Linear/Matrix"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](g_net/custom_fully_connected_1/Linear/Matrix, save/RestoreV2_48)]]

ubuntu@ip-Address:~/StackGAN$
```

**Comment by hanzhanggit** [comment]
Thanks for the interests to the work. Currently, for our pre-trained model, the spatial size for stack-I image is 64 * 64 and 256 * 256 for the stack-II image. We have not tried higher resolution yet. If you have interests in generating higher resolution image, you can train the model by yourself by changing the yml file. Or even have more stacks, but it is helpful to make sure that the batch size you pick fits for the GPU memory.

**Comment by hanzhanggit** [comment]
It depends on the network structure you use. For the current one, it takes 2~3 days on a single TitanX Pascal. Or you can change the code to use multiple GPU for the training, it will helps reduce the training time.

**Comment by kli-nlpr** [comment]
@hanzhanggit  Could you upload your models to BaiDuYun? I can't download the models even use VPN.
Thank you very much.

**Comment by brannondorsey** [comment]
@kli-nlpr I am working on creating a docker image for this repo so that folks can get up and running with this code quickly without having to follow the install instructions. As a part of this, I've written some scripts that download the pre-trained models. I had trouble `curl`ing from google drive, so I've downloaded the models and am hosting them on [github here](https://github.com/brangerbriz/docker-StackGAN/releases) (see birds_model_164000.ckpt, flowers_model_130000.ckpt, and  birds_skip_thought_model_164000.ckpt). Hope this helps :)

**Comment by kli-nlpr** [comment]
@brannondorsey  Thank you very much

**Comment by OwalnutO** [comment]
@hanzhanggit Also about the size of the image. In stage-1, the spatial size of image is 64*64, and we hope the generator in stage-2 may receive missed information to generate the high-resolution images. I'm wandering if in stage-1 we generate image of size 256*256 and in stage-2 the generator just plays as a super-resolution mechanism with the missed information, will it works as well. How do you think about it?Have you ever tested it before?
