### ISSUE TITLE
 Stage-I GAN train error 

### ISSUE THREAD

**Issue by chaowentao** [hanzhanggit/StackGAN#44]
ubuntu 14.04
python 2.7
tensorflow 0.12.1
cuda 8.0
cudnn 5.1
when i run this
`python stageI/run_exp.py --cfg stageI/cfg/flowers.yml --gpu 0`
The error is this
`/home/cwt/StackGAN/misc/datasets.py:78: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  images[i][w1: w1 + self._imsize, h1: h1 + self._imsize, :]
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed launching ResizeNearestNeighbor
	 [[Node: g_net/apply_5/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/gpu:0"](g_net/apply_4/Relu, g_net/apply_5/ResizeNearestNeighbor/size)]]
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed launching ResizeNearestNeighbor
	 [[Node: g_net/apply_5/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/gpu:0"](g_net/apply_4/Relu, g_net/apply_5/ResizeNearestNeighbor/size)]]
Traceback (most recent call last):
  File "stageI/run_exp.py", line 68, in <module>
    algo.train()
  File "/home/cwt/StackGAN/stageI/trainer.py", line 359, in train
    feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed launching ResizeNearestNeighbor
	 [[Node: g_net/apply_5/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/gpu:0"](g_net/apply_4/Relu, g_net/apply_5/ResizeNearestNeighbor/size)]]
	 [[Node: add_1/_71 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6500_add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'g_net/apply_5/ResizeNearestNeighbor', defined at:
  File "stageI/run_exp.py", line 68, in <module>
    algo.train()
  File "/home/cwt/StackGAN/stageI/trainer.py", line 306, in train
    counter = self.build_model(sess)
  File "/home/cwt/StackGAN/stageI/trainer.py", line 280, in build_model
    self.init_opt()
  File "/home/cwt/StackGAN/stageI/trainer.py", line 101, in init_opt
    fake_images = self.model.get_generator(tf.concat(1, [c, z]))
  File "/home/cwt/StackGAN/stageI/model.py", line 145, in get_generator
    return self.generator(z_var)
  File "/home/cwt/StackGAN/stageI/model.py", line 78, in generator
    apply(tf.image.resize_nearest_neighbor, [self.s8, self.s8]).
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 1972, in method
    result = func(non_seq_layer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_methods.py", line 425, in apply_op
    operation(input_layer.tensor, *op_args, **op_kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 818, in resize_nearest_neighbor
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed launching ResizeNearestNeighbor
	 [[Node: g_net/apply_5/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/gpu:0"](g_net/apply_4/Relu, g_net/apply_5/ResizeNearestNeighbor/size)]]
	 [[Node: add_1/_71 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6500_add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`
Dear friends,can you help me ? Thanks a lot!

**Comment by 18398639574** [comment]
请问这个问题您解决了吗？
