### ISSUE TITLE
how to run the demo like the flowers_demo.sh to get the train sample ?

### ISSUE THREAD

**Issue by jononny** [hanzhanggit/StackGAN#45]
I had download all the file required, and want to see the generated samples from the example_captions; but when I run it on the environment:
linux Ubuntu 14.04.5 LTS (GNU/Linux 3.19.0-25-generic x86_64)
tensorflow 1.3.0
python 2.7

and run using the instruction like    sh demo/flowers_demo.sh
and got output and error like:
{
  doc_length : 201
  filenames : "Data/flowers/example_captions.t7"
  queries : "Data/flowers/example_captions.txt"
  net_txt : "models/text_encoder/lm_sje_flowers_c10_hybrid_0.00070_1_10_trainvalids.txt_iter16400.t7"
}
Successfully load sentences from:  Data/flowers/example_captions.t7
Total number of sentences: 8
num_embeddings: 8 (8, 1024)
2018-05-01 13:06:33.652722: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 13:06:33.652751: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 13:06:33.652760: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 13:06:33.652767: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 13:06:33.652774: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
lr_imsize:  64
Traceback (most recent call last):
  File "demo/demo.py", line 193, in <module>
    build_model(sess, embeddings.shape[-1], batch_size)
  File "demo/demo.py", line 68, in build_model
    hr_fake_images = model.hr_get_generator(fake_images, hr_c)
  File "/home1/y/StackGAN-master/stageII/model.py", line 195, in hr_get_generator
    x_c_code = tf.concat(3, [x_code, c_code])
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got <prettytensor.pretty_tensor_class.Layer object at 0x7f580cfdba90> of type 'Layer' instead.

could anyone  help me? Thanks!

**Comment by jononny** [comment]
and now I had a problem using the prettytensor-0.7.3 occur a error with AttributeError: 'module' object has no attribute 'complex_abs'
how to deal with that?

**Comment by Dragomir2020** [comment]
Try using tensorflow 0.12 and PrettyTensor 0.7.1
