### ISSUE TITLE
AttributeError: 'module' object has no attribute '_VARSCOPE_KEY'

### ISSUE THREAD

**Issue by shizhenbo** [hanzhanggit/StackGAN#51]
When I run the stageI/run_exp.py. I meet the problem as follows:
Traceback (most recent call last):
  File "/home/shizhenbo/PycharmProjects/StackGAN-master/stageI/run_exp.py", line 62, in <module>
    image_shape=dataset.image_shape
  File "/home/shizhenbo/PycharmProjects/StackGAN-master/stageI/model.py", line 34, in __init__
    self.d_encode_img_template = self.d_encode_image()
  File "/home/shizhenbo/PycharmProjects/StackGAN-master/stageI/model.py", line 164, in d_encode_image
    custom_conv2d(self.df_dim, k_h=4, k_w=4).
  File "/home/shizhenbo/.conda/envs/py27/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 1965, in method
    with _method_scope(input_layer, scope_name) as (scope, _):
  File "/home/shizhenbo/.conda/envs/py27/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/shizhenbo/.conda/envs/py27/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 1776, in _method_scope
    scopes.var_and_name_scope((name, None)) as (scope, var_scope):
  File "/home/shizhenbo/.conda/envs/py27/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/shizhenbo/.conda/envs/py27/lib/python2.7/site-packages/prettytensor/scopes.py", line 55, in var_and_name_scope
    vs_key = tf.get_collection_ref(variable_scope._VARSCOPE_KEY)
AttributeError: 'module' object has no attribute '_VARSCOPE_KEY'
Why ?
Maybe the number of lines are different to yours. Someone can help me? Thank you

**Comment by krshrimali** [comment]
I had a similar issue and solved it using `pip install tensorflow==1.7.0`. This is because of PrettyTensor incompatibility in some functions with Tensorflow's latest versions.

For more details: https://github.com/google/prettytensor/issues/62

Let me know if it doesn't work.

**Comment by jiteshpabla** [comment]
Well, it still doesn't work for me. The error stays with tensorflow versions 1.7.0, 1.4.0, 1.0 and 0.12.

**Comment by Dragomir2020** [comment]
If you are using tensorflow 0.12 I had to downgrade PrettyTensor to version 0.7.1 from 0.7.4 to get it to run. pip install prettytensor==0.7.1

**Comment by Cdeo05** [comment]
i am facing the same issue and cannot install tensorflow 1.7.0 on windows
