### ISSUE TITLE
stage-I training problem

### ISSUE THREAD

**Issue by 18398639574** [hanzhanggit/StackGAN#56]
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
Traceback (most recent call last):                                                                          |ETA:  --:--:--
  File "stageI/run_exp.py", line 78, in <module>
    algo.train()
  File "/data/sdv1/WLL/StackGAN/stageI/trainer.py", line 346, in train
    num_embedding)
  File "/data/sdv1/WLL/StackGAN/misc/datasets.py", line 144, in next_batch
    sampled_images = self.transform(sampled_images)
  File "/data/sdv1/WLL/StackGAN/misc/datasets.py", line 78, in transform
    images[i][w1: w1 + self._imsize, h1: h1 + self._imsize, :]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by akhilvasvani** [comment]
Change ```images[i][w1: w1 + self._imsize, h1: h1 + self._imsize, :]``` --> 
```images[i][int(w1): int(w1 + self._imsize), int(h1): int(h1 + self._imsize), :]```

**Comment by adigol** [comment]
It runs 6 hours and doesn't stop, is it OK?

**Comment by akhilvasvani** [comment]
Well, that depends on what you're looking for. What is your batch size?

**Comment by adigol** [comment]
I ran the original code on the birds data(about 600 batches).
I want to run it on the original data and then I'll run it on my data.

**Comment by akhilvasvani** [comment]
600 batches? I think you mean Epochs.

For me, it took about a day to train with a batch size of 64 on my NVIDIA 1080 Ti GPU. 

If you want to train StackGAN on original data (both images and captions), you need to create your own char-CNN-RNN or skip-thoughts embeddings

**Comment by priyanka1220** [comment]
can anyone please provide me the weights of stage1
