### ISSUE TITLE
Stage II Training Error 

### ISSUE THREAD

**Issue by ArunSachdev** [hanzhanggit/StackGAN#64]
Traceback (most recent call last):
  File "stageII/run_exp.py", line 60, in <module>
    algo.train()
  File "E:\StackGAN\StackGAN3\stageII\trainer.py", line 374, in train
    counter = self.build_model(sess)
  File "E:\StackGAN\StackGAN3\stageII\trainer.py", line 314, in build_model
    saver.restore(sess, self.model_path)
  File "C:\Users\Arun\Anaconda3\envs\GAN\lib\site-packages\tensorflow_core\python\training\saver.py", line 1280, in restore
    if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
  File "C:\Users\Arun\Anaconda3\envs\GAN\lib\site-packages\tensorflow_core\python\training\checkpoint_management.py", line 366, in checkpoint_exists_internal
    if file_io.get_matching_files(pathname):
  File "C:\Users\Arun\Anaconda3\envs\GAN\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\Arun\Anaconda3\envs\GAN\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: ./ckt_logs/flowers/stageI : The system cannot find the path specified.
; No such process

@akhilvasvani

**Comment by akhilvasvani** [comment]
Don't think I have generated the flower file yet
