### ISSUE TITLE
Having issues while reproducing

### ISSUE THREAD

**Issue by zzhang1987** [hanzhanggit/StackGAN#9]
When I am trying to training a GAN model by myself. I met the following issue:

Total filenames:  11788 001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg
Traceback (most recent call last):
  File "misc/preprocess_birds.py", line 101, in <module>
    convert_birds_dataset_pickle(BIRD_DIR)
  File "misc/preprocess_birds.py", line 91, in convert_birds_dataset_pickle
    train_filenames = load_filenames(train_dir)
  File "misc/preprocess_birds.py", line 27, in load_filenames
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Data/birds/train/filenames.pickle'

Where Can I find or generate the file 'Data/birds/train/filenames.pickle'?

**Comment by DrSleep** [comment]
I think you have missed this step: 

> Download our preprocessed char-CNN-RNN text embeddings for [birds](https://drive.google.com/open?id=0B3y_msrWZaXLT1BZdVdycDY5TEE) and [flowers](https://drive.google.com/open?id=0B3y_msrWZaXLaUc0UXpmcnhaVmM) and save them to `Data/`.
